

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ABD_Project
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BookingEntities : DbContext
{
    public BookingEntities()
        : base("name=BookingEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Rezervari> Rezervari { get; set; }

    public virtual DbSet<TipCamera> TipCamera { get; set; }

    public virtual DbSet<TipFacilitate> TipFacilitate { get; set; }

    public virtual DbSet<Unitati> Unitati { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<CamereOcupate> CamereOcupate { get; set; }

    public virtual DbSet<CamereUnitati> CamereUnitati { get; set; }

    public virtual DbSet<RecenziiUnitati> RecenziiUnitati { get; set; }

    public virtual DbSet<RezervariUsers> RezervariUsers { get; set; }

}

}

