
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ABD_Project
{

using System;
    using System.Collections.Generic;
    
public partial class RezervariUsers
{

    public int IDRezervare { get; set; }

    public int IDUnitate { get; set; }

    public int IDUser { get; set; }



    public virtual Rezervari Rezervari { get; set; }

    public virtual Unitati Unitati { get; set; }

    public virtual Users Users { get; set; }

}

}
