
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ABD_Project
{

using System;
    using System.Collections.Generic;
    
public partial class Rezervari
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Rezervari()
    {

        this.RezervariUsers = new HashSet<RezervariUsers>();

        this.TipFacilitate = new HashSet<TipFacilitate>();

    }


    public int IDRezervare { get; set; }

    public int IDTipCamera { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public Nullable<decimal> PretTotal { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RezervariUsers> RezervariUsers { get; set; }

    public virtual TipCamera TipCamera { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TipFacilitate> TipFacilitate { get; set; }

}

}
