//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unitati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unitati()
        {
            this.CamereDisp = new HashSet<CamereDisp>();
            this.PretCamera = new HashSet<PretCamera>();
            this.Rezervari = new HashSet<Rezervari>();
            this.TipFacilitate = new HashSet<TipFacilitate>();
        }
    
        public int IDUnitate { get; set; }
        public string Nume { get; set; }
        public string Adresa { get; set; }
        public string Oras { get; set; }
        public string Judet { get; set; }
        public int Stele { get; set; }
        public string Recenzii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamereDisp> CamereDisp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PretCamera> PretCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervari> Rezervari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipFacilitate> TipFacilitate { get; set; }
    }
}
