
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ABD_Project
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Users()
    {

        this.RecenziiUnitati = new HashSet<RecenziiUnitati>();

        this.RezervariUsers = new HashSet<RezervariUsers>();

    }


    public int IDUser { get; set; }

    public string Nume { get; set; }

    public string Prenume { get; set; }

    public string Username { get; set; }

    public string Parola { get; set; }

    public string Adresa { get; set; }

    public string Email { get; set; }

    public string Telefon { get; set; }

    public string Imagine { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RecenziiUnitati> RecenziiUnitati { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RezervariUsers> RezervariUsers { get; set; }

}

}
